version: "3.8"

services:
  dbhub:
    image: bytebase/dbhub
    container_name: dbhub
    ports:
      - "8080:8080"
    init: true
    command:
      - "--transport"
      - "sse"
      - "--port"
      - "8080"
      - "--dsn"
      - "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DATABASE}?sslmode=disable"
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
